#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Rikard Hjort <hjort@hjorthjort.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Path
#
export PATH=$HOME/depot_tools:$HOME/Code/Scripts/bin:/usr/local/bin:$PATH

# Allow completion
fpath=(~/.zsh/completion $fpath)

# gitinspector fix: provide locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

#
# Editors
#

export EDITOR='mvim'
export VISUAL='mvim'
export PAGER='less'
