#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Rikard Hjort <hjort@hjorthjort.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Allow completion
fpath=(~/.zsh/completion $fpath)

#
# Editors
#

export EDITOR='emacs'
export VISUAL='emacs'
export PAGER='less'
