#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source aliases
for file in "${ZDOTDIR:-$HOME}/.zprezto/aliases/"* ; do
  source "$file"
done

#Set unlimited history
export HISTFILESIZE=
export HISTTIMEFORMAT="[%F %T] "

#Plugins
plugins=(pacman tmux haskell fasd colored-man sudo git)

archey3
fortune
echo

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

if [ -z $(env | grep TMUX) ]; then
    tmux
fi
