#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Make MacVim default editor
export EDITOR=mvim && export VISUAL=mvim

# Define where configs folder is
export CONFIGS=~/Code/configs

# gitinspector fix: provide locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source aliases
if [[ -s "${ZDOTDIR:-$HOME}/.aliases" ]]; then
  source "${ZDOTDIR:-$HOME}/.aliases"
fi

#Set unlimited history
export HISTFILESIZE=
export HISTTIMEFORMAT="[%F %T] "

#Plugins
plugins=(fasd colored-man sudo git)

go()
{
if [ -f "$1" ]
then
    $EDITOR "$1"
else
    cd "$1" && ls
fi
}

archey
